-- AlterTable
ALTER TABLE `Blog` ADD COLUMN `OpenAIApiKey` VARCHAR(191) NULL,
    ADD COLUMN `R2AccessKeyId` VARCHAR(191) NULL,
    ADD COLUMN `R2AccountId` VARCHAR(191) NULL,
    ADD COLUMN `R2SecretAccessKey` VARCHAR(191) NULL,
    ADD COLUMN `netlifyToken` VARCHAR(191) NULL;
